### ISSUE TITLE
`level2_dau_2` not being incorporated? 

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/compressed-mirnet#8]
Referring to https://github.com/sayakpaul/compressed-mirnet/blob/main/compressed_mirnet/model/blocks/recursive_residual.py#L90

@soumik12345

**Comment by sayakpaul** [comment]
`https://github.com/sayakpaul/compressed-mirnet/blob/main/compressed_mirnet/model/blocks/recursive_residual.py#L93`

Should it have been `skff_ = SelectiveKernelFeatureFusion()(level1_dau_2, level2_dau_2, level3_dau_2)` instead?

**Comment by sayakpaul** [comment]
@soumik12345 is my understanding correct here? 

https://github.com/sayakpaul/compressed-mirnet/issues/8#issuecomment-1235457777

**Comment by soumik12345** [comment]
I think it's a typo on my part. The correct code at https://github.com/sayakpaul/compressed-mirnet/blob/main/compressed_mirnet/model/blocks/recursive_residual.py#L93 should be 

```python
skff_ = SelectiveKernelFeatureFusion()(level1_dau_2, level2_dau_2, level3_dau_2)
```

**Comment by sayakpaul** [comment]
Cool. #6 does incorporate it.

**Comment by soumik12345** [comment]
Fixed in https://github.com/sayakpaul/compressed-mirnet/pull/6
